### ISSUE TITLE
Need to enter the port every time I restart Live?! :-(

### ISSUE THREAD

**Issue by JayDeLux** [Ableton/m4l-connection-kit#12]
Hi,
I love TouchOSC. 
One thing I think is a shame is the it does not listen to the port between restart of Live: Every time I restart Live I must go to each of the TouchOSC modules I have in my set to enter the "Host port", even though it has not changed I have to go in each "port" field and enter the same port number for the connection to be reestablished with Lemur, it waists me a lot of time every time.
Am I missing something or a parameter in the configuration?
Thanks in advance.

**Comment by JayDeLux** [comment]
Hello. I thought I could give it another try as my initial explanation might not have been clear.

OSC Monitor sees the OSC messages coming in and displays them as expected.
However TouchOSC does not get them (the little led indicator next to the ‘Port’ field does not blink) **unless I manually go in its ‘Port' field and enter the port value again**.
It is really frustrating as I have to do this for each track having TouchOSC configured.
I have tried starting the OSC client (Lemur on iPad) before starting Live and the other way around (thinking there is a difference if I start the client or the server first) but it does not make any difference.

Link to a screenshot if it helps: https://ibb.co/ihsHfv

Would be greatly appreciated if anyone could help / help solve this issue. I gave a try to M4L and though I could understand how it works and fix it myself but the learning curve is so steep.

**Comment by JayDeLux** [comment]
I have posted the same on Ableton M4L form: [](https://forum.ableton.com/viewtopic.php?f=1&t=226539)

**Comment by lib-ableton** [comment]
Hi JayDeLux,

Thanks for bringing this to our attention! We're aware of this bug and have filed it on our end.

An eventual fix could be included as an update to the Connection Kit pack, although I can't provide any timeline guarantees.

In the meantime, a [live.thisdevice] patched to the Port [textedit] should help, if you'd like to edit the patch yourself.

If you have any further questions about this issue, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269)

Best regards,
Lillia
Max for Live Content Specialist
