### ISSUE TITLE
BUG - Hardcoded Firmata Standard requirement??

### ISSUE THREAD

**Issue by owlyowl** [Ableton/m4l-connection-kit#13]
Hi guys and gals.
I was wondering if anyone has tested the arduino connection kit using something other than standard firmata's name/path.

I have a random issue (tested on 2 pcs and a mac)

If I use standard firmata it works perfectly fine.

If I copy and paste the contents of standard firmata in to another sketch (with nothing else in it but standard firmata code) the connection kit doesn't work..
FirmataTest (by PJRC) totally works fine but ableton refuses to do any readings with servos sensors etc?

Can anyone from the ableton team comment?

I found this gate here.. It would appear this is the cause of the issue. Could I propose we add an advanced user checkbox or the like that allows a user to utilise any sketch they want and the checkbox bypasses the gate check?
![image](https://cloud.githubusercontent.com/assets/1916426/24970757/e1a12e66-1ff8-11e7-9dc1-60643cc37179.png)

**Comment by JRiNVENTOR** [comment]
I have this problem as well.
I can load up Standard Firmata no problem, however I cannot operate the servo connected to pin 9 of an arduino...i don't see any LED on the arduino stating that it even sees the signal coming in.
Was trying for drum bot. I've read and read and searched and can't find any solution! I've used different Uno's and even a MEGA. I don't know what the issue could be...firmware on the board?

**Comment by owlyowl** [comment]
The issue is that in the patch it is looking for a specific version of the
firmata library and if it isn't there it simply doesn't connect.. The
easiest workaround is to jump in to the connection patch and make the check
always pass I.e. at the point of check add something like OR true

Or something like OR 1 == 1

You still need to make sure all the standard firmata stuff is in your
customised sketch but it does work if you bypass the version and sketch
name check

**Comment by JRiNVENTOR** [comment]
Forgive me, I'm still new to Arduino coding...
And THANK YOU so much for getting back so quickly, it's taken me 2 days of research to no avail.

Would that be around here in the code?

 Firmata.setPinState(pin, 0);
  switch (mode) {
    case PIN_MODE_ANALOG:
      if (IS_PIN_ANALOG(pin)) {
        if (IS_PIN_DIGITAL(pin)) {
          pinMode(PIN_TO_DIGITAL(pin), INPUT);    // disable output driver
#if ARDUINO <= 100
          // deprecated since Arduino 1.0.1 - TODO: drop support in Firmata 2.6

Where am I amending this name check?
Thanks again.

**Comment by JRiNVENTOR** [comment]
Is it in the StandardFirmata sketch that I am changing something?

**Comment by JRiNVENTOR** [comment]
OK i'm in the MaxPatch and now just searching a bit more....

**Comment by JRiNVENTOR** [comment]
Mine looks like this tho....
![m4l firmata screen shot](https://user-images.githubusercontent.com/34035461/33296423-9b682408-d3a9-11e7-94b5-2702034eee89.png)

**Comment by JRiNVENTOR** [comment]
ok i've found what you were looking at....
![m4l firmata screen shot](https://user-images.githubusercontent.com/34035461/33296795-65e1c576-d3ab-11e7-92e1-550f2fa15780.png)

**Comment by JRiNVENTOR** [comment]
...Perhaps I'm getting warmer here....
Does the issue lie in the gate that you had circled in your diagram? 
Or is the problem check in the path that says "Send requests for firmware name and version to Arduino"?
I'm sorry I'm learning Arduino and Max at the same time.
It's breathtaking, really. ;)

**Comment by JRiNVENTOR** [comment]
Ok, I believe the issue to be in the gate...how then do I tell the gate to let my Arduino function the way we all want it to?

I'm going to take a break, this has been a lot of digging!
Thanks Owl.

**Comment by JRiNVENTOR** [comment]
el bumpo?

**Comment by JRiNVENTOR** [comment]
Hey guys any additional help would be amazing i'm really struggling here at this point!

**Comment by JRiNVENTOR** [comment]
el bumpo

**Comment by JRiNVENTOR** [comment]
So I take it this has nobody who knows how to fix this?

**Comment by lib-ableton** [comment]
Hi there,

We will soon be disabling this 'Issues' section, since the page is not regularly monitored.

If the Standard Firmata issue persists, please contact [Ableton Support](https://help.ableton.com/hc/requests/new?ticket_form_id=127269) and we'll be happy to help.

Best regards,
Lillia
Max for Live Content Specialist
