### ISSUE TITLE
Some settings are not saved when reopening.

### ISSUE THREAD

**Issue by snuvkin** [Ableton/m4l-connection-kit#21]
Hi,
I'm working on an RGB control with an Arduino Uno and I have a problem.
To set it up i select the port and change the digital pin to PWM and map that to something.
But when I reopen the project the mapped controls will not work, because it changed the type to input I assume, but it will still say it is in PWM mode. I have to assign the PWM mode again to get it working again. And that would be very tedious to do each time.
I assume this is a bug, or maybe I have something not setup correctly?
Thanks for your help!

**Comment by snuvkin** [comment]
This also happens when I hit rescan.

**Comment by snuvkin** [comment]
Something that is also bothering me is, that when I hit rescan. Every parameter gets disabled, I have to reenable each one to have it work again.

**Comment by snuvkin** [comment]
I am using Live 10. I just tried it in Live 9 and I'm having the same issues.

**Comment by rrryableton** [comment]
Hi Snuvkin,

Rory here from the Ableton sound team. Could you get in touch with Ableton Support (support@ableton.com) with this issue, as we do not monitor this page so often. Thanks. 

To help with the problem, it would be really great if you could reproduce it, then immediately open up the Max window, to see the logged errors. A screenshot would be very helpful. 

You can view the Max window easily by CMD / right clicking the device bar and select 'Show Max window'..  

Thanks,
Rory
